# Generated by Django 4.1.4 on 2023-04-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.CharField(max_length=20, unique=True)),
                ("answer", models.CharField(max_length=20, unique=True)),
                ("mark", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
